name: auxme_manage_JuliaCIWorkflows

on:
  # manual trigger
  workflow_dispatch:
    inputs:
      add_workflow:
        description: 'add new workflow' #'workflow from auxme/JuliaCIWorkflows to add to this repo (run empty once for update, if option is not yet available)'
        required: false
        type: choice
        options:
          - a
          - b
          - c
  pull_request:
  push:
    branches: 
      - '**'
      - '!examples'
      - '!gh-pages'
  schedule:
    - cron: '17 4 * * *'

jobs:
  update_JuliaCIWorkflows_repo:
    runs-on: ubuntu-latest
    if: github.repository == '0815creeper/JuliaCIWorkflows'
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github'
          path: working_repo
      - name: TODO!!!
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'file.yaml'
          propertyPath: 'on.workflow_dispatch.inputs.add_workflow.options'
          value: blabla
          commitChange: true
          message: 'new workflow found and added to selectable options of auxme_manage_JuliaCIWorkflows'
  manage_JuliaCIWorkflows:
    runs-on: ubuntu-latest
    if: github.repository != '0815creeper/JuliaCIWorkflows'
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github'
          path: working_repo
      - name: "Check out auxme/JuliaCIWorkflows"
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github'
          repository: 0815creeper/JuliaCIWorkflows
          path: reference_repo
      - name: handle_arguments
        if: github.event_name == 'workflow_dispatch' && inputs.add_workflow != ''
        run: echo '${{ github.event_name }} wants to add ${{ inputs.add_workflow }} workflow to this repo'
      - name: check_all_if_they_are_latest
        run: |
          FILES=( $(find working_repo/.github -type f -printf "%P\n" -iname "*.yml" | sort ) )
          for FILE in "${FILES[@]}"; do
            if [ -f reference_repo/.github/$FILE ]; then
              echo "$FILE"
              diff working_repo/.github/$FILE reference_repo/.github/$FILE
              echo $?
              echo "-------------"
            else
              echo "workflow $FILE is not part of auxme/JuliaCIWorkflows, it seems to be specific to this repo and will be ignored"
            fi
          done

      