name: auxme_manage_JuliaCIWorkflows

on:
  # manual trigger
  workflow_dispatch:
    inputs:
      add_workflow:
        description: 'add new workflow' #'workflow from auxme/JuliaCIWorkflows to add to this repo (run empty once for update, if option is not yet available)'
        required: false
        type: choice
  pull_request:
  push:
    branches: 
      - '!examples'
      - '!gh-pages'
  schedule:
    - cron: '17 4 * * *'

jobs:
  manage_JuliaCIWorkflows:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github'
          path: working_repo
      - name: "Check out auxme/JuliaCIWorkflows"
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github'
          repository: 0815creeper/JuliaCIWorkflows
          path: reference_repo
      - name: handle_arguments
        if: github.event_name == 'workflow_dispatch' && ${{ inputs.add_workflow }} != ''
        run: echo 'add ${{ inputs.add_workflow }} workflow to this repo'
      - name: check_all_if_they_are_latest
        run: tree -a
      